---
- name: Install Webserver
  hosts: all
  become: true
  tasks:
  - name: Disable SELinux 
    selinux:
      state: disabled

  - name: Disabled Firewalld
    service:
      name: firewalld
      state: stopped

  - name: Install Repository yum-utils
    yum:
      name: yum-utils
      state: latest

  - name: Install Repository epel7
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: latest

  - name: Install Repository remi7
    yum:
      name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
      state: latest

  - name: Patching RHEL7/CentOS7
    yum:
      name: "*"
      state: latest

  - name: Enable Repository PHP 7.4
    shell: yum-config-manager --enable remi-php74

  - name: Install PHP 7.4
    yum:
      name: php, php-mcrypt, php-cli, php-gd, php-curl, php-mysql, php-ldap, php-zip, php-fileinfo, php-xml, php-soap, php-xmlrpc, php-mbstring, php-json, php-gd, php-mcrypt
      state: latest

  - name: Install HTTPD Mariadb-server Memchaced CIFS-Utils etc
    yum:
      name: wget, links, httpd, mariadb-server, memcached, cifs-utils, nano, net-tools, git
      state: latest

  - name: Clone example file index from github
    shell: 
      cmd: GIT_SSL_NO_VERIFY=1 git clone https://github.com/fadharpra/template-web-maintenance.git /home/sites/public_html

  - name: Change domain name on index.html
    shell:
      cmd: sed -i "s/DOMAIN/$(cat /etc/hostname)/" /home/sites/public_html/index.html
      warn: false

  - name: Copy webserver configuration file to target host
    template:
       src: "files/website.conf"
       dest: "/etc/httpd/conf.d/website.conf"

  - name: Set Domain in website.conf file
    shell:
      cmd: sed -i "s/DOMAIN/$(cat /etc/hostname)/" /etc/httpd/conf.d/website.conf
      warn: false

  - name: Start HTTPD
    service: 
      name: httpd
      state: started

  - name: Enable HTTPD
    service:
      name: httpd
      enabled: yes

  - name: Start MariaDB
    service: 
      name: mariadb
      state: started

  - name: Enable MariaDB
    service:
      name: mariadb
      enabled: yes

